### ISSUE TITLE
Whited-out camera, using Google Pixel

### ISSUE THREAD

**Issue by ASHERH4X** [AquiGorka/webrtc-qr#1]
![Screenshot_20190319-020106](https://user-images.githubusercontent.com/38171110/54586648-b25b9780-49eb-11e9-9e10-a9d615923026.png)

Really interested in your project.  The above is what happened when I tried joining from my Google Pixel.  Tried another app (a QR code scanner) and it was normal.

**Comment by AquiGorka** [comment]
Hola @ASHERH4X, thanks for the interest.

This "whited-out" happens because the camera is rendered behind a div with certain opacity so that the user could get a preview of what the camera sees (to correctly position the phone) - I do need to improve on it.
As soon as I get some spare time I plan to include such styling improvements and a progress bar.
